theme: jekyll-theme-minimal
title: Rubing Shen
description: PhD in Sociology
mail: rubing.shen@sciencespo.fr
twitter: RubingShen
github: rubingshen
linkedin: https://www.linkedin.com/in/rubing-shen-9b84bb1b3/
googlescholar: https://scholar.google.com/citations?user=9AN4GDgAAAAJ&hl
logo : photo.HEIC
