theme: jekyll-theme-minimal
title: Rubing Shen
description: PhD Candidate in Sociology
mail: rubing.shen@sciencespo.fr
twitter: RubingShen
github: rubingshen
linkedin: https://www.linkedin.com/in/rubing-shen-9b84bb1b3/
